from django.urls import path
from . import views

urlpatterns = [
    path('', views.index,name='index'),
    path('sellerpage/', views.sellerpage,name='sellerpage'),
    
    path('sellerconfirm/', views.sellerconfirm,name='sellerconfirm'),
     path('Fashionpage/', views.Fashionpage,name='Fashionpage'),
  
    path('Fashionconfirm/', views.Fashionconfirm,name='Fashionconfirm'),
     path('Industrialproductspage/', views.Industrialproductspage,name='Industrialproductspage'),
   
    path('Industrialproductsconfirm/', views.Industrialproductsconfirm,name='Industrialproductsconfirm'),
     path('HealthProductspage/', views.HealthProductspage,name='HealthProductspage'),
   
    path('HealthProductsconfirm/', views.HealthProductsconfirm,name='HealthProductsconfirm'),
     path('HomeDecorpage/', views.HomeDecorpage,name='HomeDecorpage'),
    
    path('HomeDecorconfirm/', views.HomeDecorconfirm,name='HomeDecorconfirm'),
     path('Sportspage/', views.Sportspage,name='Sportspage'),
    
    path('Sportsconfirm/', views.Sportsconfirm,name='Sportsconfirm'),
     path('Entertainmentpage/', views.Entertainmentpage,name='Entertainmentpage'),
   
    path('Entertainmentconfirm/', views.Entertainmentconfirm,name='Entertainmentconfirm'),
     path('LuggageBagspage/', views.LuggageBagspage,name='LuggageBagspage'),
   
    path('LuggageBagsconfirm/', views.LuggageBagsconfirm,name='LuggageBagsconfirm'),
     path('Shoespage/', views.Shoespage,name='Shoespage'),
   
    path('Shoesconfirm/', views.Shoesconfirm,name='Shoesconfirm'),
     path('WatchJewelrypage/', views.WatchJewelrypage,name='WatchJewelrypage'),
 
    path('WatchJewelryconfirm/', views.WatchJewelryconfirm,name='WatchJewelryconfirm'),
     path('KidsToyspage/', views.KidsToyspage,name='KidsToyspage'),
    
    path('KidsToysconfirm/', views.KidsToysconfirm,name='KidsToysconfirm'),
     path('Watchpage/', views.Watchpage,name='Watchpage'),
    path('Luggagepage/', views.Luggagepage,name='Luggagepage'),
    path('Shoepage/', views.Shoepage,name='Shoepage'),
     path('Enterpage/', views.Enterpage,name='Enterpage'),
    path('Sportpage/', views.Sportpage,name='Sportpage'),
    path('Homepage/', views.Homepage,name='Homepage'),
     path('Healthpage', views.Healthpage,name='Healthpage'),
    path('Industrialpage/', views.Industrialpage,name='Industrialpage'),
    path('Fashionp/', views.Fashionp,name='Fashionp'),
    path('Kidspage/', views.Kidspage,name='Kidspage'),
     path('productdetail/<int:id>/', views.productdetail,name='productdetail'),
     path('industrydetail/<int:id>/', views.industrydetail,name='industrydetail'),
    path('Healthdetail/<int:id>/', views.Healthdetail,name='Healthdetail'),
     path('sportdetail/<int:id>/', views.sportdetail,name='sportdetail'),
    path('enterdetail/<int:id>/', views.enterdetail,name='enterdetail'),
     path('shoedetail/<int:id>/', views.shoedetail,name='shoedetail'),
    path('luggagedetail/<int:id>/', views.luggagedetail,name='luggagedetail'),
     path('jeweldetail/<int:id>/', views.jeweldetail,name='jeweldetail'),
    path('kidsdetail/<int:id>/', views.kidsdetail,name='kidsdetail'),
     path('Homedetail/<int:id>/', views.Homedetail,name='Homedetail'),
     path('buyform/', views.buyform,name='buyform'),
     path('paymentform/', views.paymentform,name='paymentform'),
     path('networkform/', views.networkform,name='networkform'),
      path('vodacompay/', views.vodacompay,name='vodacompay'),
     path('airtelpay/', views.airtelpay,name='airtelpay'),
     path('tigopay/', views.tigopay,name='tigopay'),
     path('halotelpay/', views.halotelpay,name='halotelpay'),
      path('Adminhomepage/', views.Adminhomepage,name='Adminhomepage'),
        path('Fashionconfirm/<int:product_id>/', views.Fashionconfirm, name='Fashionconfirm'),
        path('Registerpage/', views.Registerpage,name='Registerpage'),
        path('loginpage/', views.loginpage,name='loginpage'),
        path('logout/', views.logout,name='logout'),
        path('cart/', views.cart_detail,name='cart_detail'),
 path('Fashionbuyer/add/<int:fashion_id>/', views.Fashionbuyer,name='Fashionbuyer'),
 path('Industrybuyer/add/<int:industry_id>/', views.Industrybuyer,name='Industrybuyer'),
  path('Healthbuyer/add/<int:health_id>/', views.Healthbuyer,name='Healthbuyer'),
 path('Homebuyer/add/<int:home_id>/', views.Homebuyer,name='Homebuyer'),
  path('Sportsbuyer/add/<int:sports_id>/', views.Sportsbuyer,name='Sportsbuyer'),
 path('Entertainmentbuyer/add/<int:entertainment_id>/', views.Entertainmentbuyer,name='Entertainmentbuyer'),
  path('Luggagebuyer/add/<int:luggage_id>/', views.Luggagebuyer,name='Luggagebuyer'),
 path('Shoesbuyer/add/<int:shoes_id>/', views.Shoesbuyer,name='Shoesbuyer'),
  path('Kidsbuyer/add/<int:kids_id>/', views.Kidsbuyer,name='Kidsbuyer'),
 path('Watchbuyer/add/<int:watch_id>/', views.Watchbuyer,name='Watchbuyer'),
  path('Buyerdetail/', views.Buyerdetail, name='Buyerdetail'),
  path('industrybuyer/', views.industrybuyer,name='industrybuyer'),
   path('healthbuyer/', views.healthbuyer,name='healthbuyer'),
 path('homebuyer/', views.homebuyer,name='homebuyer'),
  path('sportbuyer/', views.sportbuyer,name='sportbuyer'),
 path('entertainbuyer/', views.entertainbuyer,name='entertainbuyer'),
  path('luggagebuyer/', views.luggagebuyer, name='luggagebuyer'),
  path('shoebuyer/', views.shoebuyer,name='shoebuyer'),
   path('kidsbuyer/', views.kidsbuyer, name='kidsbuyer'),
  path('watchbuyer/', views.watchbuyer,name='watchbuyer'),
  path('Fashionseller/', views.Fashionseller,name='Fashionseller'),
    path('Industryseller/', views.Industryseller,name='Industryseller'),
      path('Healthseller/', views.Healthseller,name='Healthseller'),
        path('Homeseller/', views.Homeseller,name='Homeseller'),
          path('Sportsseller/', views.Sportsseller,name='Sportsseller'),
            path('Shoeseller/', views.Shoeseller,name='Shoeseller'),
              path('Entertainmentseller/', views.Entertainmentseller,name='Entertainmentseller'),
                path('Luggageseller/', views.Luggageseller,name='Luggageseller'),
                  path('Kidsseller/', views.Kidsseller,name='Kidsseller'),
                    path('Watchseller/', views.Watchseller,name='Watchseller'),
     path('deletefashion/<int:id>/', views.deletefashion,name='deletefashion'),
      path('deletefashionsells/<int:id>/', views.deletefashionsells,name='deletefashionsells'),
       path('deleteindustrysells/<int:id>/', views.deleteindustrysells,name='deleteindustrysells'),
        path('deletehealthsells/<int:id>/', views.deletehealthsells,name='deletehealthsells'),
       path('deletehomesells/<int:id>/', views.deletehomesells,name='deletehomesells'),
        path('deletesportsells/<int:id>/', views.deletesportsells,name='deletesportsells'),
       path('deleteluggagesells/<int:id>/', views.deleteluggagesells,name='deleteluggagesells'),
        path('deleteshoessells/<int:id>/', views.deleteshoessells,name='deleteshoessells'),
       path('deleteentertainmentsells/<int:id>/', views.deleteentertainmentsells,name='deleteentertainmentsells'),
        path('deletekidssells/<int:id>/', views.deletekidssells,name='deletekidssells'),
       path('deletewatchsells/<int:id>/', views.deleteindustrysells,name='deletewatchsells'),
        path('buyersite', views.buyersite,name='buyersite'),
       path('sellersite', views.sellersite,name='sellersite'),
      
      path('profile/<int:p_id>/', views.profile,name='profile'),
      path ('fashionbrand/',views.fashionbrand,name='fashionbrand'),
       path ('industrybrand/',views.industrybrand,name='industrybrand'),    
        path ('healthbrand/',views.healthbrand,name='healthbrand'),    
         path ('Homebrand/',views.Homebrand,name='Homebrand'),    
          path ('sportsbrand/',views.sportsbrand,name='sportsbrand'),    
           path ('entertainmentbrand/',views.entertainmentbrand,name='entertainmentbrand'),    
            path ('shoesbrand/',views.shoesbrand,name='shoesbrand'),    
             path ('luggagebrand/',views.luggagebrand,name='luggagebrand'),    
             path ('watchbrand/',views.watchbrand,name='watchbrand'),
              path ('kidsbrand/',views.kidsbrand,name='kidsbrand'),  
              path('Cartdetail/',views.Cartdetails,name='Cartdetail'),
               path('Cartdetailed/',views.Cartdetailed,name='Cartdetailed'),      
               path('delivery/',views.delivery,name='delivery'), 
                path('CartAdmin/',views.CartAdminsite,name='CartAdmin'), 
                path('CartAdminshow/',views.CartAdminshow,name='CartAdminshow'),      
                     path('userdetail/',views.userdetail,name='userdetail'),      
       
       ]
